[PHP]
post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 120
memory_limit = 256M
date.timezone = "Asia/Tokyo"
sys_temp_dir = "/tmp"
upload_tmp_dir = "/tmp"
session.save_path = "/tmp"
